// Generated by CoffeeScript 1.6.3
(function() {
  var Database, MongoDatabase, Server, mongo;

  mongo = require("mongodb");

  Server = mongo.Server;

  MongoDatabase = mongo.Db;

  Database = (function() {
    function Database(name, host, port) {
      var _this = this;
      this.name = name;
      this.host = host != null ? host : "localhost";
      this.port = port != null ? port : 27017;
      this.server = new Server(this.host, this.port, {
        auto_reconnect: true
      });
      this.db = new MongoDatabase(this.name, this.server, {
        safe: false
      });
      this.db.open(function(err, db) {
        if (!err) {
          return console.log("Connected to todos_db database");
        } else {
          return console.log("An error ocurred: " + err);
        }
      });
    }

    Database.prototype.all = function(callback) {
      var _this = this;
      return this.db.collection(this.name, {
        strict: true
      }, function(err, collection) {
        if (!err) {
          return collection.find().toArray(function(err, items) {
            if (!err) {
              return callback(items);
            } else {
              callback({
                "error": "Couldn't retrive " + _this.name + " collection"
              });
              return console.log("Couldn't retrive todos collection");
            }
          });
        } else {
          return callback({
            "error": "Couldn't connect to " + _this.name + " collection"
          });
        }
      });
    };

    Database.prototype.read = function(id, callback) {};

    Database.prototype["delete"] = function(id, callback) {};

    Database.prototype.update = function(id, callback) {};

    Database.prototype.create = function(callback) {};

    return Database;

  })();

  module.exports = Database;

}).call(this);
