// Generated by CoffeeScript 1.6.3
(function() {
  var Database, MongoDatabase, Server, mongo;

  mongo = require("mongodb");

  Server = mongo.Server;

  MongoDatabase = mongo.Db;

  Database = (function() {
    function Database() {}

    Database["new"] = function(name, host, port) {
      this.name = name;
      this.host = host != null ? host : "localhost";
      this.port = port != null ? port : 27017;
      this.server = new Server(this.host, this.port, {
        auto_reconnect: true
      });
      this.query = new MongoDatabase(this.name, this.server, {
        safe: true
      });
      return this.query;
    };

    Database.open = function(callback) {
      var _this = this;
      return this.query.open(function(err, db) {
        if (!err) {
          return console.log("Connected to todos_db database");
        } else {
          return console.log("An error ocurred: " + err);
        }
      });
    };

    return Database;

  })();

  module.exports = Database;

}).call(this);
