// Generated by CoffeeScript 1.6.3
(function() {
  var App, express, todos;

  express = require("express");

  todos = require("./routes/todos");

  App = (function() {
    function App() {
      var _this = this;
      this.app = express();
      this.app.configure(function() {
        _this.app.set("title", "TodoMVC");
        _this.app.use(function(req, res, next) {
          console.log(req.method, req.url);
          return next();
        });
        _this.app.use(express.logger("dev"));
        return _this.app.use(express.bodyParser());
      });
      this.routes();
      this.server();
    }

    App.prototype.routes = function() {
      this.app.get("/todos", todos.all);
      this.app.get("/todos/:id", todos.read);
      this.app.post("/todos", todos.create);
      this.app.put("/todos/:id", todos.update);
      return this.app["delete"]("/todos/:id", todos["delete"]);
    };

    App.prototype.server = function() {
      this.app.listen(3000);
      return console.log("Listening on port 3000");
    };

    return App;

  })();

  new App();

}).call(this);
