// Generated by CoffeeScript 1.6.3
(function() {
  var App, express, todos;

  express = require("express");

  todos = require("./routes/todos");

  App = (function() {
    function App() {
      this.app = express();
      this.app.set("title", "TodoMVC");
      this.app.use(express.logger("dev"));
      this.app.use(express.bodyParser());
      this.app.all("/*", function(req, res, next) {
        res.header("Access-Control-Allow-Origin", "*");
        res.header("Access-Control-Allow-Headers", "Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With");
        res.header("Access-Control-Allow-Methods", "GET, PUT, POST, DELETE");
        return next();
      });
      this.app.all("/*", function(req, res, next) {
        if (req.method.toLowerCase() !== "options") {
          return next();
        }
        return res.send(204);
      });
      this.routes();
      this.server();
    }

    App.prototype.routes = function() {
      this.app.get("/todos", todos.all);
      this.app.get("/todos/:id", todos.read);
      this.app.post("/todos", todos.create);
      this.app.put("/todos/:id", todos.update);
      return this.app["delete"]("/todos/:id", todos["delete"]);
    };

    App.prototype.server = function() {
      this.app.listen(process.env.PORT || 5000);
      return console.log("Listening on port 5000");
    };

    return App;

  })();

  new App();

}).call(this);
