// Generated by CoffeeScript 1.6.3
(function() {
  var MongoDatabase, Server, Todos, mongo,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  mongo = require("mongodb");

  Server = mongo.Server;

  MongoDatabase = mongo.Db;

  Todos = (function() {
    function Todos() {
      this["delete"] = __bind(this["delete"], this);
      this.update = __bind(this.update, this);
      this.create = __bind(this.create, this);
      this.read = __bind(this.read, this);
      this.all = __bind(this.all, this);
      var _this = this;
      this.server = new Server("localhost", 27017, {
        auto_reconnect: true
      });
      this.db = new MongoDatabase("todos_db", this.server, {
        safe: true
      });
      this.db.open(function(err, db) {
        if (!err) {
          return console.log("Connected to todos_db database");
        } else {
          return console.log("An error ocurred: " + err);
        }
      });
    }

    Todos.prototype.all = function(req, res) {
      var _this = this;
      return this.db.collection("todos", {
        strict: true
      }, function(err, collection) {
        if (!err) {
          return collection.find().toArray(function(err, items) {
            if (!err) {
              return res.send(items);
            } else {
              return console.log("Couldn't retrive todos collection");
            }
          });
        } else {
          return console.log("An error ocurred: " + err);
        }
      });
    };

    Todos.prototype.read = function() {
      return console.log("READ");
    };

    Todos.prototype.create = function(req, res) {
      var todo,
        _this = this;
      todo = req.body;
      return this.db.collection("todos", function(err, collection) {
        if (!err) {
          return collection.insert(todo, {
            safe: true
          }, function(err, result) {
            if (!err) {
              console.log("Success: " + (JSON.stringify(result[0])));
              return res.send(result[0]);
            } else {
              return res.send({
                "error": "An error has ocurred"
              });
            }
          });
        } else {
          return console.log("Error adding a todo: " + err);
        }
      });
    };

    Todos.prototype.update = function() {
      return console.log("UPDATE");
    };

    Todos.prototype["delete"] = function() {
      return console.log("DELETE");
    };

    return Todos;

  })();

  module.exports = new Todos;

}).call(this);
