// Generated by CoffeeScript 1.6.3
(function() {
  var BSON, Database, Todos, mongo,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Database = require("../database/database");

  mongo = require("mongodb");

  BSON = mongo.BSONPure;

  Todos = (function() {
    Todos.prototype.name = "todos";

    function Todos() {
      this["delete"] = __bind(this["delete"], this);
      this.update = __bind(this.update, this);
      this.create = __bind(this.create, this);
      this.read = __bind(this.read, this);
      this.all = __bind(this.all, this);
      this.db = new Database(this.name);
    }

    Todos.prototype.all = function(req, res) {
      var _this = this;
      return this.db.all(function(result, error) {
        return res.send(result);
      });
    };

    Todos.prototype.read = function(req, res) {
      var id,
        _this = this;
      id = req.params.id;
      console.log("Retrieving todo " + id);
      return this.db.read(id, function(result, error) {
        if (!error) {
          result.id = result._id;
          return res.send(result);
        } else {
          return res.send(error);
        }
      });
    };

    Todos.prototype.create = function(req, res) {
      var todo,
        _this = this;
      todo = req.body;
      return this.db.create(todo, function(result, error) {
        if (!error) {
          result.id = result._id;
          return res.send(result);
        } else {
          return res.send(error);
        }
      });
    };

    Todos.prototype.update = function(req, res) {
      var id, todo,
        _this = this;
      id = req.params.id;
      todo = req.body;
      console.log("Updating todo " + id);
      console.log(JSON.stringify(todo));
      return this.db.update(id, todo, function(result, error) {
        if (!error) {
          result.id = result._id;
          return res.send(result);
        } else {
          return res.send(error);
        }
      });
    };

    Todos.prototype["delete"] = function(req, res) {
      var id,
        _this = this;
      id = req.params.id;
      console.log("Deleting todo " + id);
      return this.db["delete"](id, function(result, error) {
        if (!error) {
          result.id = result._id;
          return res.send(result);
        } else {
          return res.send(error);
        }
      });
    };

    return Todos;

  })();

  module.exports = new Todos;

}).call(this);
